services:
  zailom-oficial:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zailom-oficial
    restart: unless-stopped
    networks:
      - zailom-ofc

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=zailom-ofc"

      # HTTP -> HTTPS
      - "traefik.http.routers.zailom-oficial-http.rule=Host(`zailom.com`) || Host(`www.zailom.com`)"
      - "traefik.http.routers.zailom-oficial-http.entrypoints=web"
      - "traefik.http.routers.zailom-oficial-http.middlewares=zailom-oficial-redirect"
      - "traefik.http.middlewares.zailom-oficial-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.zailom-oficial-redirect.redirectscheme.permanent=true"

      # HTTPS
      - "traefik.http.routers.zailom-oficial.rule=Host(`zailom.com`) || Host(`www.zailom.com`)"
      - "traefik.http.routers.zailom-oficial.entrypoints=websecure"
      - "traefik.http.routers.zailom-oficial.tls=true"
      - "traefik.http.routers.zailom-oficial.tls.certresolver=leresolver"
      - "traefik.http.routers.zailom-oficial.service=zailom-oficial"

      - "traefik.http.services.zailom-oficial.loadbalancer.server.port=3000"

networks:
  zailom-ofc:
    external: true
